server:
  port: 8080
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
spring:
  application:
    name: api-gateway-service
  cloud:
    gateway:
      routes:
        - id: budget-service
          uri: lb://budget-service
          predicates:
            - Path=/budget-service/api/**
        - id: notification-service
          uri: lb://notification-service
          predicates:
            - Path=/notification-service/api/**
        - id: expense-service
          uri: lb://expense-service
          predicates:
            - Path=/expense-service/api/**

logging:
  level:
    org:
      springframework:
        cloud:
          gateway:
            route:
              RouteDefinitionLocator : INFO
